spring:
  datasource:
    url: jdbc:h2:file:~/data;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: Kabaye
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
customer:
  money-precision: 100
