server:
  port: 8663

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loader_db
    username: dbaas_7b93a74a9a204326bcd2848465ffb915
    password: f86a0f9c38f84feab5bdbeb3a6a21e77

management:
  metrics:
    enable:
      http:
        client:
          requests: false
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans,caches,health,httptrace,info,metrics,mappings,sessions,shutdown,threaddump,env,prometheus
      base-path: /monitor